### ISSUE TITLE
Error in website home page

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/website#604]
This issue is to address the error found in the [home page](https://chaoss.community/) of CHAOSS -

The link to WG-common on this page points to Metrics repository instead,
There is already [this commit](https://github.com/chaoss/website/commit/fc0a7b39ee170810661d7dc570823abc687c24fd) by Matt G that fixed this issue, but the same is not reflected on the website, possibly because the website is pulling from a different branch than master?

Also, currently, [this markdown](https://github.com/chaoss/website/blob/master/Home/working-groups.md) shows 5 Working Groups, while 6 are listed on the website (again, due to different branch maybe)..
Should wg-app-ecosystem be added to this markdown on master branch as well?

@klumb WDYT?

**Comment by klumb** [comment]
Thanks @ritik-malik 
I fixed the link on the website.

In general, this issue is the result of a prior problem we had with the GitHub Sync element. On 3 occasions, we have lost our WordPress connection to GitHub. 

The result of this was that the content on the home page was created in parallel to what is in the repo.

The website migration should prevent futures issues we have with this so - we need to reconnect the Wordpress elements to the GitHub Markdown files.

Todo:
1. make sure the content in the GitHub markdown files matches what is currently on the homepage.
2. once this is done, I will remove the current homepage content and reconnect it to GitHub.

**Comment by ritik-malik** [comment]
Hi @klumb ,
That explains it well.

I just checked the website again, but it is still showing `metrics` link instead of `wg-common`.
Is it because it takes some time to reflect the changes or again some Sync problem?

Also, should I add `wg-app-ecosystem` to displayed Working Groups in [this markdown](https://github.com/chaoss/website/blob/master/Home/working-groups.md), as you said we need to match the content in Github markdown & the website.
WDYT?

**Comment by klumb** [comment]
Weird. I cleared the server cache on my end. Working for me. Try again and let me know.

**Comment by klumb** [comment]
Also, yes I would add the wg-app-ecosystem to the list. While their work is a little different, they do define themselves as a working group so our content should reflect that.

**Comment by ritik-malik** [comment]
Yes, it is showing the updated link now, maybe needed to wait for a while,
also, I added the link to WG-app-ecosystem in #606

**Comment by ritik-malik** [comment]
I think we can close this issue now,
thanks @klumb
